apiVersion: v1
kind: Service
metadata:
  name: ngnix
  labels:
    app: ngnix
    env: dev
spec:
  selector:
    app: ngnix
  ports:
    - port: 80 
      protocol: TCP
      targetPort: 8080
  type: ClusterIP