apiVersion: v1
kind: Pod
metadata:
  labels: 
    run: frontend
    service: webserver
  name: frontend 
spec:
  containers:
  - image: nginx
    name: nginx
    args:
    - sleep
    - "1800"
    volumeMounts:
    - mountPath: /web
      name: vol-web
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: vol-web
    emptyDir:
      sizeLimit: 256Mi
---
apiVersion: v1
kind: Pod
metadata:
  labels: 
    run: server-api
    service: server-api-web
  name: server-api
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "1800"
    volumeMounts:
    - mountPath: /api-server
      name: vol-api-server
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: vol-api-server
    emptyDir:
      sizeLimit: 256Mi