apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: limited
  name: limited
spec:
  replicas: 5
  selector:
    matchLabels:
      app: limited
  template:
    metadata:
      labels:
        app: limited
    spec:
      containers:
      - image: nginx:1.16.0
        name: nginxru
        resources:
          limits:
            cpu: "500m"
            memory: 256Mi
          requests:
            cpu: "0.25"
            memory: 128Mi